// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /amd/lnxdata311/nfs/data41/t2k/amissert/atmos/sytools/./histoManager.h;
#pragma link C++ defined_in "/amd/lnxdata311/nfs/data41/t2k/amissert/atmos/sytools/./histoManager.C";

#endif
