/********************************************************************
* /amd/lnxdata311/nfs/data41/t2k/amissert/atmos/sytools/histoFactory_C_ACLiC_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /amd/lnxdata311/nfs/data41/t2k/amissert/atmos/sytools/histoFactory_C_ACLiC_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablehistoFactory_C_ACLiC_dict();
extern void G__cpp_setup_inheritancehistoFactory_C_ACLiC_dict();
extern void G__cpp_setup_typetablehistoFactory_C_ACLiC_dict();
extern void G__cpp_setup_memvarhistoFactory_C_ACLiC_dict();
extern void G__cpp_setup_globalhistoFactory_C_ACLiC_dict();
extern void G__cpp_setup_memfunchistoFactory_C_ACLiC_dict();
extern void G__cpp_setup_funchistoFactory_C_ACLiC_dict();
extern void G__set_cpp_environmenthistoFactory_C_ACLiC_dict();
}


#include "/tmp/rootcint_GCOPZ8.h"
