//
// File generated by /nfs/data40/t2k/amissert/ROOT2/root/bin/rootcint at Thu Aug  4 16:34:05 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dInfsdIdata41dIt2kdIamissertdIatmosdIheaddIatmFitToolsdImcmcReader_cxx_ACLiC_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "mcmcReader_cxx_ACLiC_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::mcmcReader mcmcReader;
      #else
      class mcmcReader  {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~mcmcReader() throw() {};
         ::TTree* fChain; //!pointer to the analyzed TTree or TChain
         int fCurrent; //!current Tree number in a TChain
         int npars; //
         int step; //
         double par[100]; //
         ::TBranch* b_npars; //!
         ::TBranch* b_step; //!
         ::TBranch* b_par; //!
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void mcmcReader_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void mcmcReader_Dictionary();
   static void *new_mcmcReader(void *p = 0);
   static void *newArray_mcmcReader(Long_t size, void *p);
   static void delete_mcmcReader(void *p);
   static void deleteArray_mcmcReader(void *p);
   static void destruct_mcmcReader(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::mcmcReader*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::mcmcReader) == sizeof(::ROOT::Shadow::mcmcReader));
      ::mcmcReader *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::mcmcReader),0);
      static ::ROOT::TGenericClassInfo 
         instance("mcmcReader", "/nfs/data41/t2k/amissert/atmos/head/atmFitTools/./mcmcReader.h", 15,
                  typeid(::mcmcReader), DefineBehavior(ptr, ptr),
                  &mcmcReader_ShowMembers, &mcmcReader_Dictionary, isa_proxy, 4,
                  sizeof(::mcmcReader) );
      instance.SetNew(&new_mcmcReader);
      instance.SetNewArray(&newArray_mcmcReader);
      instance.SetDelete(&delete_mcmcReader);
      instance.SetDeleteArray(&deleteArray_mcmcReader);
      instance.SetDestructor(&destruct_mcmcReader);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::mcmcReader*)
   {
      return GenerateInitInstanceLocal((::mcmcReader*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::mcmcReader*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void mcmcReader_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::mcmcReader*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void mcmcReader_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class mcmcReader.
      typedef ::ROOT::Shadow::mcmcReader ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::mcmcReader*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fChain", &sobj->fChain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCurrent", &sobj->fCurrent);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "npars", &sobj->npars);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "step", &sobj->step);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "par[100]", sobj->par);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_npars", &sobj->b_npars);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_step", &sobj->b_step);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_par", &sobj->b_par);
   }

}

namespace ROOT {
   // Wrappers around operator new
   static void *new_mcmcReader(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::mcmcReader : new ::mcmcReader;
   }
   static void *newArray_mcmcReader(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::mcmcReader[nElements] : new ::mcmcReader[nElements];
   }
   // Wrapper around operator delete
   static void delete_mcmcReader(void *p) {
      delete ((::mcmcReader*)p);
   }
   static void deleteArray_mcmcReader(void *p) {
      delete [] ((::mcmcReader*)p);
   }
   static void destruct_mcmcReader(void *p) {
      typedef ::mcmcReader current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::mcmcReader

/********************************************************
* /nfs/data41/t2k/amissert/atmos/head/atmFitTools/mcmcReader_cxx_ACLiC_dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablemcmcReader_cxx_ACLiC_dict();

extern "C" void G__set_cpp_environmentmcmcReader_cxx_ACLiC_dict() {
  G__cpp_reset_tagtablemcmcReader_cxx_ACLiC_dict();
}
#include <new>
extern "C" int G__cpp_dllrevmcmcReader_cxx_ACLiC_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* mcmcReader */
static int G__mcmcReader_cxx_ACLiC_dict_3239_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   mcmcReader* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new mcmcReader((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) mcmcReader((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new mcmcReader[n];
       } else {
         p = new((void*) gvp) mcmcReader[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new mcmcReader;
       } else {
         p = new((void*) gvp) mcmcReader;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_mcmcReader));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcmcReader_cxx_ACLiC_dict_3239_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((mcmcReader*) G__getstructoffset())->Cut((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcmcReader_cxx_ACLiC_dict_3239_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((mcmcReader*) G__getstructoffset())->GetEntry((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcmcReader_cxx_ACLiC_dict_3239_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letLonglong(result7, 110, (G__int64) ((mcmcReader*) G__getstructoffset())->LoadTree((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcmcReader_cxx_ACLiC_dict_3239_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mcmcReader*) G__getstructoffset())->Init((TTree*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcmcReader_cxx_ACLiC_dict_3239_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mcmcReader*) G__getstructoffset())->Loop();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcmcReader_cxx_ACLiC_dict_3239_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((mcmcReader*) G__getstructoffset())->Notify());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcmcReader_cxx_ACLiC_dict_3239_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((mcmcReader*) G__getstructoffset())->Show((Long64_t) G__Longlong(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((mcmcReader*) G__getstructoffset())->Show();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__mcmcReader_cxx_ACLiC_dict_3239_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   mcmcReader* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new mcmcReader(*(mcmcReader*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_mcmcReader));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef mcmcReader G__TmcmcReader;
static int G__mcmcReader_cxx_ACLiC_dict_3239_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (mcmcReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((mcmcReader*) (soff+(sizeof(mcmcReader)*i)))->~G__TmcmcReader();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (mcmcReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((mcmcReader*) (soff))->~G__TmcmcReader();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__mcmcReader_cxx_ACLiC_dict_3239_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   mcmcReader* dest = (mcmcReader*) G__getstructoffset();
   *dest = *(mcmcReader*) libp->para[0].ref;
   const mcmcReader& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* mcmcReader */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmcmcReader_cxx_ACLiC_dict {
 public:
  G__Sizep2memfuncmcmcReader_cxx_ACLiC_dict(): p(&G__Sizep2memfuncmcmcReader_cxx_ACLiC_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmcmcReader_cxx_ACLiC_dict::*p)();
};

size_t G__get_sizep2memfuncmcmcReader_cxx_ACLiC_dict()
{
  G__Sizep2memfuncmcmcReader_cxx_ACLiC_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemcmcReader_cxx_ACLiC_dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemcmcReader_cxx_ACLiC_dict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* mcmcReader */
static void G__setup_memvarmcmcReader(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_mcmcReader));
   { mcmcReader *p; p=(mcmcReader*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->fCurrent)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fCurrent=",0,"!current Tree number in a TChain");
   G__memvar_setup((void*)((long)(&p->npars)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"npars=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->step)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"step=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->par)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"par[100]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_npars)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_TBranch),-1,-1,1,"b_npars=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_step)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_TBranch),-1,-1,1,"b_step=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_par)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_TBranch),-1,-1,1,"b_par=",0,"!");
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmcmcReader_cxx_ACLiC_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncmcmcReader(void) {
   /* mcmcReader */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_mcmcReader));
   G__memfunc_setup("mcmcReader",1011,G__mcmcReader_cxx_ACLiC_dict_3239_0_1, 105, G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_mcmcReader), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' tree", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Cut",300,G__mcmcReader_cxx_ACLiC_dict_3239_0_2, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,G__mcmcReader_cxx_ACLiC_dict_3239_0_3, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LoadTree",784,G__mcmcReader_cxx_ACLiC_dict_3239_0_4, 110, -1, G__defined_typename("Long64_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,G__mcmcReader_cxx_ACLiC_dict_3239_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Loop",410,G__mcmcReader_cxx_ACLiC_dict_3239_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,G__mcmcReader_cxx_ACLiC_dict_3239_0_7, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Show",417,G__mcmcReader_cxx_ACLiC_dict_3239_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "n - 'Long64_t' 0 '-1' entry", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("mcmcReader", 1011, G__mcmcReader_cxx_ACLiC_dict_3239_0_9, (int) ('i'), G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_mcmcReader), -1, 0, 1, 1, 1, 0, "u 'mcmcReader' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~mcmcReader", 1137, G__mcmcReader_cxx_ACLiC_dict_3239_0_10, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__mcmcReader_cxx_ACLiC_dict_3239_0_11, (int) ('u'), G__get_linked_tagnum(&G__mcmcReader_cxx_ACLiC_dictLN_mcmcReader), -1, 1, 1, 1, 1, 0, "u 'mcmcReader' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmcmcReader_cxx_ACLiC_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalmcmcReader_cxx_ACLiC_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcmcmcReader_cxx_ACLiC_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__mcmcReader_cxx_ACLiC_dictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__mcmcReader_cxx_ACLiC_dictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__mcmcReader_cxx_ACLiC_dictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__mcmcReader_cxx_ACLiC_dictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__mcmcReader_cxx_ACLiC_dictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__mcmcReader_cxx_ACLiC_dictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__mcmcReader_cxx_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__mcmcReader_cxx_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mcmcReader_cxx_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__mcmcReader_cxx_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mcmcReader_cxx_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__mcmcReader_cxx_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__mcmcReader_cxx_ACLiC_dictLN_mcmcReader = { "mcmcReader" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemcmcReader_cxx_ACLiC_dict() {
  G__mcmcReader_cxx_ACLiC_dictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__mcmcReader_cxx_ACLiC_dictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__mcmcReader_cxx_ACLiC_dictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__mcmcReader_cxx_ACLiC_dictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__mcmcReader_cxx_ACLiC_dictLN_TBranch.tagnum = -1 ;
  G__mcmcReader_cxx_ACLiC_dictLN_TTree.tagnum = -1 ;
  G__mcmcReader_cxx_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__mcmcReader_cxx_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mcmcReader_cxx_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__mcmcReader_cxx_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mcmcReader_cxx_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__mcmcReader_cxx_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__mcmcReader_cxx_ACLiC_dictLN_mcmcReader.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemcmcReader_cxx_ACLiC_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__mcmcReader_cxx_ACLiC_dictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mcmcReader_cxx_ACLiC_dictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__mcmcReader_cxx_ACLiC_dictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mcmcReader_cxx_ACLiC_dictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__mcmcReader_cxx_ACLiC_dictLN_TBranch);
   G__get_linked_tagnum_fwd(&G__mcmcReader_cxx_ACLiC_dictLN_TTree);
   G__get_linked_tagnum_fwd(&G__mcmcReader_cxx_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__mcmcReader_cxx_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mcmcReader_cxx_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__mcmcReader_cxx_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mcmcReader_cxx_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__mcmcReader_cxx_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__mcmcReader_cxx_ACLiC_dictLN_mcmcReader),sizeof(mcmcReader),-1,296192,(char*)NULL,G__setup_memvarmcmcReader,G__setup_memfuncmcmcReader);
}
extern "C" void G__cpp_setupmcmcReader_cxx_ACLiC_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupmcmcReader_cxx_ACLiC_dict()");
  G__set_cpp_environmentmcmcReader_cxx_ACLiC_dict();
  G__cpp_setup_tagtablemcmcReader_cxx_ACLiC_dict();

  G__cpp_setup_inheritancemcmcReader_cxx_ACLiC_dict();

  G__cpp_setup_typetablemcmcReader_cxx_ACLiC_dict();

  G__cpp_setup_memvarmcmcReader_cxx_ACLiC_dict();

  G__cpp_setup_memfuncmcmcReader_cxx_ACLiC_dict();
  G__cpp_setup_globalmcmcReader_cxx_ACLiC_dict();
  G__cpp_setup_funcmcmcReader_cxx_ACLiC_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmcmcReader_cxx_ACLiC_dict();
  return;
}
class G__cpp_setup_initmcmcReader_cxx_ACLiC_dict {
  public:
    G__cpp_setup_initmcmcReader_cxx_ACLiC_dict() { G__add_setup_func("mcmcReader_cxx_ACLiC_dict",(G__incsetup)(&G__cpp_setupmcmcReader_cxx_ACLiC_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initmcmcReader_cxx_ACLiC_dict() { G__remove_setup_func("mcmcReader_cxx_ACLiC_dict"); }
};
G__cpp_setup_initmcmcReader_cxx_ACLiC_dict G__cpp_setup_initializermcmcReader_cxx_ACLiC_dict;

